# Generated by Django 3.2.3 on 2021-05-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='site_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
