# Generated by Django 4.1.1 on 2022-09-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_holidays',
            field=models.BooleanField(default=False, verbose_name="Exibir 'feriado'"),
        ),
    ]
