# Generated by Django 5.1.8 on 2026-07-04 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_show_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key_used', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('url_name', models.CharField(blank=True, default='', max_length=64)),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=8)),
                ('status_code', models.PositiveSmallIntegerField(default=0)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='core.profile')),
            ],
            options={
                'verbose_name': 'API request log',
                'verbose_name_plural': 'API request logs',
                'indexes': [models.Index(fields=['profile', 'timestamp'], name='core_apireq_profile_e97955_idx'), models.Index(fields=['api_key_used', 'timestamp'], name='core_apireq_api_key_57ac19_idx')],
            },
        ),
    ]
