# Generated by Django 5.1.8 on 2026-07-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_apirequestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestlog',
            name='cf_connecting_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='referer',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
